[tool.briefcase]
project_name = "Benevis"
bundle = "org.poido"
version = "0.0.9"
url = "https://github.com/ecmel/benevis"
license = "MIT license"
author = 'Ecmel Ercan'
author_email = "ecmel.ercan@gmail.com"

[tool.briefcase.app.benevis]
formal_name = "Benevis"
description = "Easy Dictation"
icon = "src/benevis/resources/benevis"
sources = ['src/benevis']
requires = [
    'sounddevice==0.4.4',
    'vosk==0.3.32'
]

[tool.briefcase.app.benevis.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.benevis.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.benevis.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.benevis.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.benevis.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
