name: Create App Bundle

on:
  release:
    types:
      - created

jobs:
  bundle:
    name: Bundle on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2    
        with:
          path: briefcase
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd briefcase
          python -m pip install .
          python -m pip freeze
      - name: Create and Build Bundle
        run: |
          cd benevis
          briefcase package --no-sign
          