name: Create App Bundle

on:
  release:
    types:
      - created

jobs:
  bundle:
    name: Bundle on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2    
        with:
          path: briefcase
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Package
        run: |
          cd briefcase
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip freeze
          cd benevis
          python -m briefcase package --no-sign
      - name: macOS
        if: runner.os == 'macOS'
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'macOS/*.dmg'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
